Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,6 +20,18 @@ jobs:
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
         script: |
+          # Check if ansible exists, if not install
+          if ! command -v ansible &> /dev/null
+          then
+            echo "Ansible not found. Installing..."
+            sudo apt update
+            sudo apt install software-properties-common -y
+            sudo add-apt-repository --yes --update ppa:ansible/ansible
+            sudo apt install ansible -y
+          else
+            echo "Ansible is already installed."
+          fi
+
+          # Proceed with your deployment
           cd /home/ubuntu/pearlThoughts
           ansible-playbook -i inventory.ini playbook.yml
-
